# Generated by Django 5.2.3 on 2025-06-26 19:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the budget item (e.g., 'Monthly Rent', 'Car Insurance')", max_length=200)),
                ('owner', models.CharField(help_text='Owner of this budget item', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Monetary amount for the budget item (minimum $0.01)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('repeats', models.BooleanField(default=False, help_text='Whether this budget item repeats')),
                ('startdate', models.DateField(help_text='Start date for this budget item')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for when this budget item should stop', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Item',
                'verbose_name_plural': 'Budget Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The month this instance represents (use first day of month)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount for all items in this month', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this monthly instance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_items', models.ManyToManyField(blank=True, help_text='Budget items included in this month', to='budgets.budgetitem')),
            ],
            options={
                'verbose_name': 'Monthly Instance',
                'verbose_name_plural': 'Monthly Instances',
                'ordering': ['-month'],
                'unique_together': {('month',)},
            },
        ),
    ]
